### ISSUE TITLE
Log files overwriting when "reuse = True"

### ISSUE THREAD

**Issue by ryanlutz-cx** [anthony-tuininga/cx_Logging#3] opened 2021-02-11 23:37 UTC
We've run into a bug where it would occasionally overwrite log files even when "reuse = True". To work around this, we've replaced 

`state->fp = fopen(state->fileName, "w");`
with 
```
if (state->reuseExistingFiles)
    state->fp = fopen(state->fileName, "w");
else
    state->fp = _fsopen(state->fileName, "w", _SH_DENYWR);
```

and this has resolved our issue. Since we are specifying the shflag parameter, we also had to include share.h. 

Is there any possibility that this could be added to master as well? If you did add it, we would be able to use the source master instead of a forked version.

**Comment by anthony-tuininga** [comment] 2021-02-13 20:50
I'd be happy to do so, but the issue is that `_fsopen()` is not portable. If you want to do this solely for Windows, please supply a patch or create a pull request that you can confirm works on Windows and doesn't break compatibliity on non-Windows platforms! Thanks.

**Comment by deymundson-cx** [comment] 2021-03-04 18:50
@anthony-tuininga I'm looking into creating a PR for this. Is it acceptable to simply fall back to the old behaviour on non-Windows platforms?
i.e.
```C
#ifdef MS_WINDOWS
    if (state->reuseExistingFiles)
        state->fp = fopen(state->fileName, "w");
    else
        state->fp = _fsopen(state->fileName, "w", _SH_DENYWR);
#else
    state->fp = fopen(state->fileName, "w");
#endif
```

**Comment by marcelotduarte** [comment] 2021-04-05 04:18
@deymundson If it compiles in windows with MSVC and MinGW, and others systems, it is portable.

**Comment by anthony-tuininga** [comment] 2021-04-09 03:40
@deymundson, that would be acceptable, sure. Can you create a pull request?

**Comment by anthony-tuininga** [comment] 2022-11-12 01:53
Fix merged.

**Closed as completed by anthony-tuininga** 2022-11-12 01:53 UTC
